name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          # We can test version by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version

      - name: Install dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build

      - name: Test with dotnet
        run: dotnet test